#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-cli-nspkg
Version  : 3.0.4
Release  : 2
URL      : https://files.pythonhosted.org/packages/ff/4c/f4042805fe07ee2196c903bdd2dcae152b21d3a1404bb6033dec23e883c1/azure-cli-nspkg-3.0.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/ff/4c/f4042805fe07ee2196c903bdd2dcae152b21d3a1404bb6033dec23e883c1/azure-cli-nspkg-3.0.4.tar.gz
Summary  : Microsoft Azure CLI Namespace Package
Group    : Development/Tools
License  : MIT
Requires: azure-cli-nspkg-python = %{version}-%{release}
Requires: azure-cli-nspkg-python3 = %{version}-%{release}
Requires: azure-nspkg
BuildRequires : azure-nspkg
BuildRequires : buildreq-distutils3

%description
=====================================
        
        This is the Microsoft Azure CLI namespace package.
        
        This package is not intended to be installed directly by the end user.
        
        It provides the necessary files for other packages to extend the azure cli namespaces.

%package python
Summary: python components for the azure-cli-nspkg package.
Group: Default
Requires: azure-cli-nspkg-python3 = %{version}-%{release}

%description python
python components for the azure-cli-nspkg package.


%package python3
Summary: python3 components for the azure-cli-nspkg package.
Group: Default
Requires: python3-core
Provides: pypi(azure_cli_nspkg)
Requires: pypi(azure_nspkg)

%description python3
python3 components for the azure-cli-nspkg package.


%prep
%setup -q -n azure-cli-nspkg-3.0.4
cd %{_builddir}/azure-cli-nspkg-3.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588721051
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.8/site-packages/azure/cli/__init__.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/azure/cli/__pycache__/__init__.cpython-38.pyc

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
